import './globals.css'
import styles from './layout.module.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className={styles.header}>
  <div>
   <h1 style={{ marginTop: 0 }}>From layout</h1>
  </div>
 <div>
<Link href="/profile/teacher">navigate to teacher profile</Link>
  </div>
  <div>
    <Link href="/profile/student">navigate to student profile</Link>
  </div>
</div>
        <div className="">
        {children}
        </div>
        </body>
    </html>
  )
}
