import styles from '../layout.module.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    
      <div
          className={styles.innerLayout}
        >
        <div>
        Announcements: Tomorrow is a holiday!
      </div>
      <div>
        {children}
      </div>
        </div>
    </html>
  )
}


